"""Uren & meerwerk — steigerbouw-tak (BOUW GO Peter 2026-08-21, fase 1).

Besluiten (BESLISSINGEN "Ontwerpronde uren & uitvoerder + meerwerk-kantoor"): weekstaat PER
PROJECT (één staat per persoon per project per ISO-week), KEURING OP WEEKNIVEAU (akkoord óf
afkeuren met verplichte reden → hele week terug als "corrigeren"), goedgekeurd = getekende
urenstaat (onmuteerbaar), nieuwe rol DETACHEERDER (vult in namens gekoppelde ZZP'ers —
vervangt teamleider/manager uit 17-08), meerwerk gemeld → goedgekeurd-nog-doorbelasten →
doorbelast/afgewezen-met-reden, module-recht "Meerwerk & urenstaten" per kantoormedewerker
(0019-patroon), opt-in per administratie (alleen Universal initieel).

Onderdelen:
1. Drie nieuwe waarden op platform.gebruiker_rol: zzper / uitvoerder / detacheerder
   (externe app-rollen op de 0040-lijn — zie app/auth/rollen.py). NB een PG-enum-waarde kan
   niet verwijderd worden; de downgrade laat ze staan (zelfde beperking als 0040).
2. CHECK-uitbreiding platform.gebruiker_module_rol: module 'boekhouding' met rol
   'meerwerk_urenstaten' (het kantoor-module-recht; 0034 voorzag deze uitbreiding expliciet).
3. Opt-in platform.administratie.uren_meerwerk_ingeschakeld (default UIT — patroon 0051).
4. platform.detacheerder_koppeling (persoonsniveau, analoog gebruiker_entiteit): RLS — de
   detacheerder leest zijn eigen rijen, muteren is Beheerder-only; audit via de service.
5. Domeintabellen in boekhouding (weekstaat, weekstaat_dag, meerwerk,
   uren_project_toewijzing, project_specificatie, project_document, project_staffel) —
   allemaal administratie-gebonden mét RLS (helper-patroon 0033). Geen DELETE-grants behalve
   op de koppel-/configuratietabellen uren_project_toewijzing en project_staffel; weekstaten,
   dagregels, meerwerk en projectdocumenten verdwijnen nooit ("niets verdwijnt stil").

Revision ID: 0056
Revises: 0055
Create Date: 2026-08-21

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0056'
down_revision: str | None = '0055'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

APP_ROLE = "boekhouding_app"

# Rolwaarden per module (CHECK op platform.gebruiker_module_rol) — de volledige, actuele set:
# 0034 introduceerde 'vastgoed'; deze migratie voegt 'boekhouding' toe met het module-recht
# "Meerwerk & urenstaten". Uitbreiden = opnieuw een vervolg-migratie (bewust expliciet).
MODULE_ROLLEN = {
    "vastgoed": ("superadmin", "eigenaar", "kantoor"),
    "boekhouding": ("meerwerk_urenstaten",),
}
MODULE_ROLLEN_VOOR_0056 = {
    "vastgoed": ("superadmin", "eigenaar", "kantoor"),
}


def _check_clausule(module_rollen: dict[str, tuple[str, ...]]) -> str:
    delen = [
        "(module = '{m}' AND rol IN ({r}))".format(m=m, r=", ".join(f"'{rol}'" for rol in rollen))
        for m, rollen in module_rollen.items()
    ]
    return " OR ".join(delen)


def _rls_op_administratie(tabel: str, *, grants: str = "SELECT, INSERT, UPDATE") -> None:
    op.execute(f"ALTER TABLE boekhouding.{tabel} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE boekhouding.{tabel} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY {tabel}_scope ON boekhouding.{tabel}
        USING (administratie_id = platform.current_administratie_id())
        WITH CHECK (administratie_id = platform.current_administratie_id())
        """
    )
    op.execute(f"GRANT {grants} ON boekhouding.{tabel} TO {APP_ROLE}")


def upgrade() -> None:
    # --- 1. nieuwe rollen (PG >= 12: ADD VALUE mag in een transactie zolang de waarde niet in
    # dezelfde transactie gebruikt wordt — deze migratie is puur DDL, dus dat is geborgd) ------
    op.execute("ALTER TYPE platform.gebruiker_rol ADD VALUE IF NOT EXISTS 'zzper'")
    op.execute("ALTER TYPE platform.gebruiker_rol ADD VALUE IF NOT EXISTS 'uitvoerder'")
    op.execute("ALTER TYPE platform.gebruiker_rol ADD VALUE IF NOT EXISTS 'detacheerder'")

    # --- 2. module-recht "Meerwerk & urenstaten" (CHECK-uitbreiding, voorzien in 0034) --------
    op.drop_constraint("ck_gebruiker_module_rol_geldig", "gebruiker_module_rol", schema="platform")
    op.create_check_constraint(
        "ck_gebruiker_module_rol_geldig",
        "gebruiker_module_rol",
        _check_clausule(MODULE_ROLLEN),
        schema="platform",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detacheerder_koppeling',
    sa.Column('detacheerder_gebruiker_id', sa.UUID(), nullable=False),
    sa.Column('zzper_gebruiker_id', sa.UUID(), nullable=False),
    sa.Column('aangemaakt_door', sa.UUID(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aangemaakt_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['detacheerder_gebruiker_id'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['zzper_gebruiker_id'], ['platform.gebruiker.id'], ),
    sa.PrimaryKeyConstraint('detacheerder_gebruiker_id', 'zzper_gebruiker_id'),
    schema='platform'
    )
    op.create_index('ix_detacheerder_koppeling_zzper', 'detacheerder_koppeling', ['zzper_gebruiker_id'], unique=False, schema='platform')
    op.create_table('meerwerk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('omschrijving', sa.Text(), nullable=False),
    sa.Column('aantal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('eenheid', sa.Text(), nullable=False),
    sa.Column('datum_uitgevoerd', sa.Date(), nullable=False),
    sa.Column('in_opdracht_van', sa.Text(), nullable=True),
    sa.Column('foto_opslag_pad', sa.Text(), nullable=True),
    sa.Column('foto_bestandsnaam', sa.Text(), nullable=True),
    sa.Column('foto_content_type', sa.Text(), nullable=True),
    sa.Column('gemeld_door', sa.UUID(), nullable=False),
    sa.Column('gemeld_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('prijs_per_eenheid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bedrag', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('facturatie_notitie', sa.Text(), nullable=True),
    sa.Column('beoordeeld_door', sa.UUID(), nullable=True),
    sa.Column('beoordeeld_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('afwijs_reden', sa.Text(), nullable=True),
    sa.Column('doorbelast_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verkoopfactuur_referentie', sa.Text(), nullable=True),
    sa.Column('vraag_tekst', sa.Text(), nullable=True),
    sa.Column('vraag_gesteld_door', sa.UUID(), nullable=True),
    sa.Column('vraag_gesteld_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vraag_antwoord', sa.Text(), nullable=True),
    sa.Column('vraag_beantwoord_op', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("eenheid IN ('m2', 'm1', 'stuks', 'manuren')", name='ck_meerwerk_eenheid'),
    sa.CheckConstraint("status != 'afgewezen' OR afwijs_reden IS NOT NULL", name='ck_meerwerk_afwijs_reden'),
    sa.CheckConstraint("status != 'doorbelast' OR verkoopfactuur_referentie IS NOT NULL", name='ck_meerwerk_doorbelast_referentie'),
    sa.CheckConstraint("status IN ('gemeld', 'goedgekeurd', 'doorbelast', 'afgewezen')", name='ck_meerwerk_status'),
    sa.CheckConstraint("status NOT IN ('goedgekeurd', 'doorbelast') OR (prijs_per_eenheid IS NOT NULL AND bedrag IS NOT NULL)", name='ck_meerwerk_prijs_bevestigd'),
    sa.CheckConstraint('aantal > 0', name='ck_meerwerk_aantal'),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['beoordeeld_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['gemeld_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'administratie_id'], ['boekhouding.project_cache.id', 'boekhouding.project_cache.administratie_id'], name='fk_meerwerk_project_cache'),
    sa.ForeignKeyConstraint(['vraag_gesteld_door'], ['platform.gebruiker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='boekhouding'
    )
    op.create_index('ix_meerwerk_administratie_id', 'meerwerk', ['administratie_id'], unique=False, schema='boekhouding')
    op.create_index('ix_meerwerk_administratie_status', 'meerwerk', ['administratie_id', 'status'], unique=False, schema='boekhouding')
    op.create_table('project_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('soort', sa.Text(), nullable=False),
    sa.Column('titel', sa.Text(), nullable=False),
    sa.Column('versie_omschrijving', sa.Text(), nullable=True),
    sa.Column('opslag_pad', sa.Text(), nullable=False),
    sa.Column('bestandsnaam', sa.Text(), nullable=False),
    sa.Column('geupload_door', sa.UUID(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("soort IN ('contract', 'offerte')", name='ck_project_document_soort'),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['geupload_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'administratie_id'], ['boekhouding.project_cache.id', 'boekhouding.project_cache.administratie_id'], name='fk_project_document_project_cache'),
    sa.PrimaryKeyConstraint('id'),
    schema='boekhouding'
    )
    op.create_index('ix_project_document_administratie_id', 'project_document', ['administratie_id'], unique=False, schema='boekhouding')
    op.create_index('ix_project_document_project', 'project_document', ['administratie_id', 'project_id'], unique=False, schema='boekhouding')
    op.create_table('project_specificatie',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.Column('opdrachtgever', sa.Text(), nullable=True),
    sa.Column('werknummer_opdrachtgever', sa.Text(), nullable=True),
    sa.Column('soort_werk', sa.Text(), nullable=True),
    sa.Column('contract_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('looptijd_van', sa.Date(), nullable=True),
    sa.Column('looptijd_tot', sa.Date(), nullable=True),
    sa.Column('huurtijd_omschrijving', sa.Text(), nullable=True),
    sa.Column('doorlopende_huur_omschrijving', sa.Text(), nullable=True),
    sa.Column('bijgewerkt_door', sa.UUID(), nullable=False),
    sa.Column('bijgewerkt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['bijgewerkt_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'administratie_id'], ['boekhouding.project_cache.id', 'boekhouding.project_cache.administratie_id'], name='fk_project_specificatie_project_cache'),
    sa.PrimaryKeyConstraint('project_id', 'administratie_id'),
    schema='boekhouding'
    )
    op.create_table('project_staffel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('omschrijving', sa.Text(), nullable=False),
    sa.Column('eenheid', sa.Text(), nullable=False),
    sa.Column('prijs_per_eenheid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('verrekenbaar', sa.Boolean(), nullable=False),
    sa.Column('bron', sa.Text(), nullable=True),
    sa.Column('aangemaakt_door', sa.UUID(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("eenheid IN ('m2', 'm1', 'stuks', 'manuren')", name='ck_project_staffel_eenheid'),
    sa.CheckConstraint('prijs_per_eenheid >= 0', name='ck_project_staffel_prijs'),
    sa.ForeignKeyConstraint(['aangemaakt_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'administratie_id'], ['boekhouding.project_cache.id', 'boekhouding.project_cache.administratie_id'], name='fk_project_staffel_project_cache'),
    sa.PrimaryKeyConstraint('id'),
    schema='boekhouding'
    )
    op.create_index('ix_project_staffel_administratie_id', 'project_staffel', ['administratie_id'], unique=False, schema='boekhouding')
    op.create_index('ix_project_staffel_project', 'project_staffel', ['administratie_id', 'project_id'], unique=False, schema='boekhouding')
    op.create_table('uren_project_toewijzing',
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.Column('gebruiker_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('toegevoegd_door', sa.UUID(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['gebruiker_id'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'administratie_id'], ['boekhouding.project_cache.id', 'boekhouding.project_cache.administratie_id'], name='fk_uren_project_toewijzing_project_cache'),
    sa.ForeignKeyConstraint(['toegevoegd_door'], ['platform.gebruiker.id'], ),
    sa.PrimaryKeyConstraint('administratie_id', 'gebruiker_id', 'project_id'),
    schema='boekhouding'
    )
    op.create_index('ix_uren_project_toewijzing_administratie_id', 'uren_project_toewijzing', ['administratie_id'], unique=False, schema='boekhouding')
    op.create_table('weekstaat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.Column('gebruiker_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('jaar', sa.SmallInteger(), nullable=False),
    sa.Column('weeknummer', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('ingediend_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingediend_door', sa.UUID(), nullable=True),
    sa.Column('goedgekeurd_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('goedgekeurd_door', sa.UUID(), nullable=True),
    sa.Column('afgekeurd_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('afgekeurd_door', sa.UUID(), nullable=True),
    sa.Column('afkeur_reden', sa.Text(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bijgewerkt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status != 'corrigeren' OR afkeur_reden IS NOT NULL", name='ck_weekstaat_afkeur_reden'),
    sa.CheckConstraint("status != 'goedgekeurd' OR (goedgekeurd_op IS NOT NULL AND goedgekeurd_door IS NOT NULL)", name='ck_weekstaat_goedgekeurd_velden'),
    sa.CheckConstraint("status IN ('concept', 'ingediend', 'goedgekeurd', 'corrigeren')", name='ck_weekstaat_status'),
    sa.CheckConstraint('weeknummer BETWEEN 1 AND 53', name='ck_weekstaat_weeknummer'),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['afgekeurd_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['gebruiker_id'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['goedgekeurd_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['ingediend_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'administratie_id'], ['boekhouding.project_cache.id', 'boekhouding.project_cache.administratie_id'], name='fk_weekstaat_project_cache'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('administratie_id', 'gebruiker_id', 'project_id', 'jaar', 'weeknummer', name='uq_weekstaat_persoon_project_week'),
    schema='boekhouding'
    )
    op.create_index('ix_weekstaat_administratie_id', 'weekstaat', ['administratie_id'], unique=False, schema='boekhouding')
    op.create_index('ix_weekstaat_administratie_status', 'weekstaat', ['administratie_id', 'status'], unique=False, schema='boekhouding')
    op.create_index('ix_weekstaat_gebruiker', 'weekstaat', ['administratie_id', 'gebruiker_id'], unique=False, schema='boekhouding')
    op.create_table('weekstaat_dag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekstaat_id', sa.UUID(), nullable=False),
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('uren', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('opmerking', sa.Text(), nullable=True),
    sa.Column('ingevuld_door', sa.UUID(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bijgewerkt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('m2 IS NULL OR m2 >= 0', name='ck_weekstaat_dag_m2'),
    sa.CheckConstraint('uren >= 0 AND uren <= 24', name='ck_weekstaat_dag_uren'),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['ingevuld_door'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['weekstaat_id'], ['boekhouding.weekstaat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekstaat_id', 'datum', name='uq_weekstaat_dag_datum'),
    schema='boekhouding'
    )
    op.create_index('ix_weekstaat_dag_administratie_id', 'weekstaat_dag', ['administratie_id'], unique=False, schema='boekhouding')
    op.create_index('ix_weekstaat_dag_weekstaat_id', 'weekstaat_dag', ['weekstaat_id'], unique=False, schema='boekhouding')
    op.add_column(
        'administratie',
        sa.Column('uren_meerwerk_ingeschakeld', sa.Boolean(), nullable=False, server_default=sa.false()),
        schema='platform',
    )
    # ### end Alembic commands ###

    # --- RLS + GRANTs -------------------------------------------------------------------------
    # Administratie-gebonden domeintabellen (patroon 0033). DELETE alleen op de koppel-/
    # configuratietabellen; weekstaten/dagen/meerwerk/projectdocumenten verdwijnen nooit.
    _rls_op_administratie("weekstaat")
    _rls_op_administratie("weekstaat_dag")
    _rls_op_administratie("meerwerk")
    _rls_op_administratie("uren_project_toewijzing", grants="SELECT, INSERT, DELETE")
    _rls_op_administratie("project_specificatie")
    _rls_op_administratie("project_document")
    _rls_op_administratie("project_staffel", grants="SELECT, INSERT, UPDATE, DELETE")

    # platform.detacheerder_koppeling: persoonsniveau — de detacheerder leest zijn eigen
    # rijen, muteren is Beheerder-only (0019-lijn; audit via de service). ENABLE zonder FORCE
    # (zelfde afweging als 0034: de eigenaar/migraties blijven ongescoped).
    op.execute("ALTER TABLE platform.detacheerder_koppeling ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY detacheerder_koppeling_lees ON platform.detacheerder_koppeling
        FOR SELECT USING (
            detacheerder_gebruiker_id = platform.current_actor_id()
            OR platform.current_actor_is_beheerder()
        )
        """
    )
    op.execute(
        """
        CREATE POLICY detacheerder_koppeling_toevoegen ON platform.detacheerder_koppeling
        FOR INSERT WITH CHECK (platform.current_actor_is_beheerder())
        """
    )
    op.execute(
        """
        CREATE POLICY detacheerder_koppeling_verwijderen ON platform.detacheerder_koppeling
        FOR DELETE USING (platform.current_actor_is_beheerder())
        """
    )
    op.execute(f"GRANT SELECT, INSERT, DELETE ON platform.detacheerder_koppeling TO {APP_ROLE}")


def downgrade() -> None:
    # CHECK terug naar de 0034-vorm. NB: eventuele 'boekhouding'-rijen moeten dan al weg zijn
    # (downgrade faalt anders hard — bewust, nooit stil rechten laten vervallen). De drie
    # enum-waarden blijven staan: PostgreSQL kent geen ALTER TYPE ... DROP VALUE (zelfde
    # beperking als 0040 met 'wacht_op_passkey').
    op.drop_constraint("ck_gebruiker_module_rol_geldig", "gebruiker_module_rol", schema="platform")
    op.create_check_constraint(
        "ck_gebruiker_module_rol_geldig",
        "gebruiker_module_rol",
        _check_clausule(MODULE_ROLLEN_VOOR_0056),
        schema="platform",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administratie', 'uren_meerwerk_ingeschakeld', schema='platform')
    op.drop_index('ix_weekstaat_dag_weekstaat_id', table_name='weekstaat_dag', schema='boekhouding')
    op.drop_index('ix_weekstaat_dag_administratie_id', table_name='weekstaat_dag', schema='boekhouding')
    op.drop_table('weekstaat_dag', schema='boekhouding')
    op.drop_index('ix_weekstaat_gebruiker', table_name='weekstaat', schema='boekhouding')
    op.drop_index('ix_weekstaat_administratie_status', table_name='weekstaat', schema='boekhouding')
    op.drop_index('ix_weekstaat_administratie_id', table_name='weekstaat', schema='boekhouding')
    op.drop_table('weekstaat', schema='boekhouding')
    op.drop_index('ix_uren_project_toewijzing_administratie_id', table_name='uren_project_toewijzing', schema='boekhouding')
    op.drop_table('uren_project_toewijzing', schema='boekhouding')
    op.drop_index('ix_project_staffel_project', table_name='project_staffel', schema='boekhouding')
    op.drop_index('ix_project_staffel_administratie_id', table_name='project_staffel', schema='boekhouding')
    op.drop_table('project_staffel', schema='boekhouding')
    op.drop_table('project_specificatie', schema='boekhouding')
    op.drop_index('ix_project_document_project', table_name='project_document', schema='boekhouding')
    op.drop_index('ix_project_document_administratie_id', table_name='project_document', schema='boekhouding')
    op.drop_table('project_document', schema='boekhouding')
    op.drop_index('ix_meerwerk_administratie_status', table_name='meerwerk', schema='boekhouding')
    op.drop_index('ix_meerwerk_administratie_id', table_name='meerwerk', schema='boekhouding')
    op.drop_table('meerwerk', schema='boekhouding')
    op.drop_index('ix_detacheerder_koppeling_zzper', table_name='detacheerder_koppeling', schema='platform')
    op.drop_table('detacheerder_koppeling', schema='platform')
    # ### end Alembic commands ###
