"""Factuurmatch ZZP-/bureaufacturen — fase 1 (verkenning + fasering akkoord Peter 2026-08-21).

Besluiten (BESLISSINGEN "FACTUURMATCH ZZP-/BUREAUFACTUREN"):
1. Bureau-tarief per detacheerder↔zzp'er-koppeling = HOOFDMECHANISME van de bureaufactuurmatch
   (bureaus factureren per ZZP'er verschillende tarieven) — kolom uurtarief op
   platform.detacheerder_koppeling. Ontbrekend tarief = match alleen op uren, oranje "geen
   tarief bekend", geen blokkade. Het losse ZZP-tarief staat op de veldwerker-koppeling.
2. Boeken bij afwijking = toestaan mét expliciete bevestiging (fase 2); autoboek-slot strikt
   groen incl. bedrag (fase 4).
3. Afwijking = losse vlag + eigen teller/chip (duplicaat-patroon) — géén nieuwe enum-status,
   dus geen document_status-uitbreiding hier.
4. Autoboek-opt-in per veldwerker-koppeling (veldwerker_crediteur.autoboeken_ingeschakeld,
   default UIT).

Onderdelen:
1. boekhouding.veldwerker_crediteur — veldwerker↔RLZ-crediteur per administratie (uniek per
   crediteur), mét ZZP-uurtarief en de autoboek-opt-in. Koppel-/configuratietabel: RLS op
   administratie, grants incl. UPDATE en DELETE (patroon uren_project_toewijzing/staffel).
2. boekhouding.factuurmatch + factuurmatch_staat — het matchresultaat per document en de
   betrokken staten van de laatste berekening. Herberekening ververst (factuurmatch: UPDATE,
   staat-rijen: DELETE+INSERT); factuurmatch zelf kent geen DELETE ("niets verdwijnt stil").
3. weekstaat.verrekend_met_document_id/-op — dubbeltelling-preventie: bij boeken worden de
   betrokken staten aan het document verrekend; een verrekende staat telt nooit meer mee in
   een andere match.
4. platform.detacheerder_koppeling.uurtarief + UPDATE-policy/grant (tarief muteren is
   Beheerder-only, zelfde 0019-lijn als INSERT/DELETE) én een verbrede lees-policy: de
   SYSTEEM-ACTOR mag de koppelingen lezen — de match-motor draait als achtergrondverwerking
   (fase 2) en moet de bureau-tarieven kunnen optellen (patroon 0016/0034: vaste actor-id).

Revision ID: 0057
Revises: 0056
Create Date: 2026-08-21

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0057'
down_revision: str | None = '0056'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

APP_ROLE = "boekhouding_app"
SYSTEEM_ACTOR_ID = "00000000-0000-0000-0000-000000000001"


def _rls_op_administratie(tabel: str, *, grants: str = "SELECT, INSERT, UPDATE") -> None:
    op.execute(f"ALTER TABLE boekhouding.{tabel} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE boekhouding.{tabel} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY {tabel}_scope ON boekhouding.{tabel}
        USING (administratie_id = platform.current_administratie_id())
        WITH CHECK (administratie_id = platform.current_administratie_id())
        """
    )
    op.execute(f"GRANT {grants} ON boekhouding.{tabel} TO {APP_ROLE}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veldwerker_crediteur',
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.Column('gebruiker_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('uurtarief', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('autoboeken_ingeschakeld', sa.Boolean(), nullable=False),
    sa.Column('gekoppeld_door', sa.UUID(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bijgewerkt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('uurtarief IS NULL OR uurtarief >= 0', name='ck_veldwerker_crediteur_uurtarief'),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['gebruiker_id'], ['platform.gebruiker.id'], ),
    sa.ForeignKeyConstraint(['gekoppeld_door'], ['platform.gebruiker.id'], ),
    sa.PrimaryKeyConstraint('administratie_id', 'gebruiker_id'),
    sa.UniqueConstraint('administratie_id', 'vendor_id', name='uq_veldwerker_crediteur_vendor'),
    schema='boekhouding'
    )
    op.create_index('ix_veldwerker_crediteur_administratie_id', 'veldwerker_crediteur', ['administratie_id'], unique=False, schema='boekhouding')
    op.create_table('factuurmatch',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.Column('veldwerker_gebruiker_id', sa.UUID(), nullable=False),
    sa.Column('uitkomst', sa.Text(), nullable=False),
    sa.Column('staten_som_uren', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('staten_som_bedrag', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('factuur_bedrag', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('factuur_uren', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('verschil_bedrag', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('verschil_uren', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tarief_ontbreekt', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('berekend_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("uitkomst IN ('match', 'match_alleen_uren', 'afwijking', 'niet_toetsbaar')", name='ck_factuurmatch_uitkomst'),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['boekhouding.document.id'], ),
    sa.ForeignKeyConstraint(['veldwerker_gebruiker_id'], ['platform.gebruiker.id'], ),
    sa.PrimaryKeyConstraint('document_id'),
    schema='boekhouding'
    )
    op.create_index('ix_factuurmatch_administratie_id', 'factuurmatch', ['administratie_id'], unique=False, schema='boekhouding')
    op.create_index('ix_factuurmatch_administratie_uitkomst', 'factuurmatch', ['administratie_id', 'uitkomst'], unique=False, schema='boekhouding')
    op.create_table('factuurmatch_staat',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('weekstaat_id', sa.UUID(), nullable=False),
    sa.Column('administratie_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['administratie_id'], ['platform.administratie.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['boekhouding.factuurmatch.document_id'], ),
    sa.ForeignKeyConstraint(['weekstaat_id'], ['boekhouding.weekstaat.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'weekstaat_id'),
    schema='boekhouding'
    )
    op.create_index('ix_factuurmatch_staat_administratie_id', 'factuurmatch_staat', ['administratie_id'], unique=False, schema='boekhouding')
    op.create_index('ix_factuurmatch_staat_weekstaat_id', 'factuurmatch_staat', ['weekstaat_id'], unique=False, schema='boekhouding')
    op.add_column('weekstaat', sa.Column('verrekend_met_document_id', sa.UUID(), nullable=True), schema='boekhouding')
    op.add_column('weekstaat', sa.Column('verrekend_op', sa.DateTime(timezone=True), nullable=True), schema='boekhouding')
    op.create_foreign_key('fk_weekstaat_verrekend_document', 'weekstaat', 'document', ['verrekend_met_document_id'], ['id'], source_schema='boekhouding', referent_schema='boekhouding')
    op.create_check_constraint(
        'ck_weekstaat_verrekend_samen',
        'weekstaat',
        '(verrekend_met_document_id IS NULL) = (verrekend_op IS NULL)',
        schema='boekhouding',
    )
    op.add_column('detacheerder_koppeling', sa.Column('uurtarief', sa.Numeric(precision=8, scale=2), nullable=True), schema='platform')
    op.create_check_constraint(
        'ck_detacheerder_koppeling_uurtarief',
        'detacheerder_koppeling',
        'uurtarief IS NULL OR uurtarief >= 0',
        schema='platform',
    )
    # ### end Alembic commands ###

    # --- RLS + GRANTs -------------------------------------------------------------------------
    # veldwerker_crediteur = koppel-/configuratietabel (patroon uren_project_toewijzing);
    # factuurmatch wordt bij herberekening ge-UPDATE't maar nooit verwijderd ("niets verdwijnt
    # stil"); de staat-rijen van een berekening worden bij herberekening vervangen (DELETE).
    _rls_op_administratie("veldwerker_crediteur", grants="SELECT, INSERT, UPDATE, DELETE")
    _rls_op_administratie("factuurmatch", grants="SELECT, INSERT, UPDATE")
    _rls_op_administratie("factuurmatch_staat", grants="SELECT, INSERT, DELETE")

    # platform.detacheerder_koppeling: tarief muteren is Beheerder-only (0019-lijn, zelfde
    # afweging als de INSERT-/DELETE-policies uit 0056).
    op.execute(
        """
        CREATE POLICY detacheerder_koppeling_muteren ON platform.detacheerder_koppeling
        FOR UPDATE USING (platform.current_actor_is_beheerder())
        WITH CHECK (platform.current_actor_is_beheerder())
        """
    )
    op.execute(f"GRANT UPDATE ON platform.detacheerder_koppeling TO {APP_ROLE}")

    # Lees-policy verbreed met de systeem-actor (match-motor als achtergrondverwerking).
    op.execute("DROP POLICY detacheerder_koppeling_lees ON platform.detacheerder_koppeling")
    op.execute(
        f"""
        CREATE POLICY detacheerder_koppeling_lees ON platform.detacheerder_koppeling
        FOR SELECT USING (
            detacheerder_gebruiker_id = platform.current_actor_id()
            OR platform.current_actor_is_beheerder()
            OR platform.current_actor_id() = '{SYSTEEM_ACTOR_ID}'
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY detacheerder_koppeling_lees ON platform.detacheerder_koppeling")
    op.execute(
        """
        CREATE POLICY detacheerder_koppeling_lees ON platform.detacheerder_koppeling
        FOR SELECT USING (
            detacheerder_gebruiker_id = platform.current_actor_id()
            OR platform.current_actor_is_beheerder()
        )
        """
    )
    op.execute(f"REVOKE UPDATE ON platform.detacheerder_koppeling FROM {APP_ROLE}")
    op.execute("DROP POLICY detacheerder_koppeling_muteren ON platform.detacheerder_koppeling")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_detacheerder_koppeling_uurtarief', 'detacheerder_koppeling', schema='platform')
    op.drop_column('detacheerder_koppeling', 'uurtarief', schema='platform')
    op.drop_constraint('ck_weekstaat_verrekend_samen', 'weekstaat', schema='boekhouding')
    op.drop_constraint('fk_weekstaat_verrekend_document', 'weekstaat', schema='boekhouding', type_='foreignkey')
    op.drop_column('weekstaat', 'verrekend_op', schema='boekhouding')
    op.drop_column('weekstaat', 'verrekend_met_document_id', schema='boekhouding')
    op.drop_index('ix_factuurmatch_staat_weekstaat_id', table_name='factuurmatch_staat', schema='boekhouding')
    op.drop_index('ix_factuurmatch_staat_administratie_id', table_name='factuurmatch_staat', schema='boekhouding')
    op.drop_table('factuurmatch_staat', schema='boekhouding')
    op.drop_index('ix_factuurmatch_administratie_uitkomst', table_name='factuurmatch', schema='boekhouding')
    op.drop_index('ix_factuurmatch_administratie_id', table_name='factuurmatch', schema='boekhouding')
    op.drop_table('factuurmatch', schema='boekhouding')
    op.drop_index('ix_veldwerker_crediteur_administratie_id', table_name='veldwerker_crediteur', schema='boekhouding')
    op.drop_table('veldwerker_crediteur', schema='boekhouding')
    # ### end Alembic commands ###
